version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
     - "9000:3000"
    volumes:
     - ./faucet-ui/nginx.conf:/etc/nginx/conf.d/default.conf
     - ./facet-ui/build:/usr/share/nginx/html
    command: /bin/bash -c "nginx -g 'daemon off;'"
  faucet:
    env_file:
      - ./.env # which copy from example.evn and filling parameter by yourself.
    build:
      context: ./faucet-server
      dockerfile: ./Dockerfile
    ports:
      - "9001:80"
    volumes:
      - ./faucet-server:/app
    command: /bin/bash -c "swift build -c release && ./.build/release/Run serve 
             --hostname 0.0.0.0
             --port 80
             --github_oauth_client_id $GITHUB_OAUTH_CLIENT_ID 
             --github_oauth_client_secret $GITHUB_OAUTH_CLIENT_SECRET
             --node_url $NODE_URL 
             --send_capacity_count $SEND_CAPACITY_COUNT
             --wallet_private_key $WALLET_PRIVATE_KEY"
